### PR TITLE
Fix for #121

### LINKED ISSUE #121: Support DataFrames 1.0
The new version of DataFrames seems to break BayesNets.jl. See this [log](https://travis-ci.org/github/sisl/BayesNets.jl/jobs/767929383).

### PR DESCRIPTION
**Pull request by dwijenchawra**
Resolved #121, rewrote deprecated DataFrame conversions

### CODE REVIEW

File: src/Factors/factors_dataframes.jl [hunk 1]
```diff
@@ -7,7 +7,7 @@
 Convert a Factor to a DataFrame
 """
 function Base.convert(::Type{DataFrame}, ϕ::Factor)
-    df = DataFrames.DataFrame(pattern(ϕ))
+    df = DataFrames.DataFrame(pattern(ϕ), :auto)
```
Comment (dwijenchawra) [inline src/Factors/factors_dataframes.jl:10]: This change breaks 0.2.1 however fixes issues in 1.*, i think leaving support for 0.21 should be fine?  It had its last  release in Oct 2020 and there are a lot more releases ahead of it

Comment (mykelk) [reply src/Factors/factors_dataframes.jl:10]: Yes, that's fine.

File: Project.toml [hunk 2]
```diff
@@ -26,7 +26,7 @@ Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
 
 
 [compat]
-DataFrames = "1.1.0"
+DataFrames = "0.22,1.0.0,1.1.0"
```
Comment (mykelk) [inline Project.toml:29]: I think we can just include major and minor version, leaving off the patch version. So, perhaps replace with `"0.22,1.0,1.1"`

**Review by mykelk — APPROVED** [review]
